// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc;

public interface BloglistOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Bloglist)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 bloglistid = 1;</code>
   */
  long getBloglistid();

  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  java.util.List<com.zemoso.grpc.Blog> 
      getBlogsList();
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  com.zemoso.grpc.Blog getBlogs(int index);
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  int getBlogsCount();
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  java.util.List<? extends com.zemoso.grpc.BlogOrBuilder> 
      getBlogsOrBuilderList();
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  com.zemoso.grpc.BlogOrBuilder getBlogsOrBuilder(
      int index);
}
